export const MODE_CHANGE: string = 'MODE_CHANGE'
export const SHOW_MENU: string = 'SHOW_MENU'
export const HIDE_MENU: string = 'HIDE_MENU'
export const NEXT_SLIDE: string = 'NEXT_SLIDE'
export const PREV_SLIDE: string = 'PREV_SLIDE'
export const ADD_COMMENTS: string = 'ADD_COMMENTS'
export const CHANGE_LANGUAGE: string = 'CHANGE_LANGUAGE'
export const SHOW_CHOSE: string = 'SHOW_CHOSE'

export const ADD_NEW_COMMENT: string = 'ADD_NEW_COMMENT'
export const ADD_NAME:string = 'ADD_NAME'
export const ADD_JOB:string = 'ADD_JOB'
export const ADD_EMAIL:string = 'ADD_EMAIL'